# Generated by Django 4.1.5 on 2023-01-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='etd',
            new_name='estimated_time_depature',
        ),
    ]
